### ISSUE TITLE
Merge test_cesar to master and cut a new release

### ISSUE THREAD

**Issue by soichih** [brain-life/app-tractanalysisprofiles#10]
BL is currently using `test_cesar` branch of this App. Should we do following?

1) merge any changes made to `test_cesar` to `master`.
2) test the `master` branch and cut `1.2` branch.
3) update BL to use 1.2 branch for "Tract Analysis Profile" and "test_tractprofiles" Apps.

Also, I am not sure what the difference between "Tract Analysis Profile" and "test_tractprofiles" is. It looks like "Tract Analysis Profile" is using NODDI? If so, maybe we can merge these 2 Apps by making NODDI output an optional input? 

Also, "Tract Analysis Profile" using using "raw:tensor" input. It should be replaced by just "tensor" input just like "test_tractprofiles" App.

**Comment by bacaron** [comment]
No one should be using “test_tractprofiles”. I can delete that now.

Sorry about the confusion!

Thank you,
Brad Caron
IU Program in Neuroscience and Program in Vision Sciences

**Comment by soichih** [comment]
@bacaron Can you create a new branch off master (maybe like "1.4"?) and point the Brainlife App to use that branch? Currently it's registerd to use "master" which could get updated without user knowing it.

**Comment by soichih** [comment]
branch 1.4 exists. closing this ticket.
