### ISSUE TITLE
Register a separate App for noddi

### ISSUE THREAD

**Issue by soichih** [brain-life/app-tractanalysisprofiles#15]
Currently, there is only 1 App registered for this repo. As the code allows user to select either tensor, or noddi, both are set to optional. This means user can submit this App without neither tensor nor noddi and the App will fail in such case.

I believe we should clone the existing registration (we can clone an App now) and update the new one to require wmc and noddi, and remove the tensor to make it a noddi specific App. And make the original registration tensor specific.

@bacaron Please let me know if you have any objection.

**Comment by bacaron** [comment]
I don't see why the app failing if the user doesn't input either is an issue. It wouldn't make sense from a user perspective anyway to not include a measure of interest for tract profiles. Having one app saves the user from A) having to know that there are separate apps for tensor and NODDI, and B) searching for the specific version they require, and C) save space on the apps page and reduce clutter. It also makes downloading the data easier if the user is using both tensor and NODDI measures, and saves space on our resources.

I don't have a strong feeling either way, but I don't think the issue presented is a pressing one.

**Comment by soichih** [comment]
I forgot that this app can take *both* inputs.. but I still think we should split it so that user can just run it twice to generate outputs with both noddi and tensor input.

I've heard from several users who are confused about why this App is not running, and in most cases, they weren't aware that they had to specify at least one *optional* inputs.By splitting up the App, Brainlife will only present the tensor or noddi version of the App that user can actually submit, and it will make sure that user will supply both inputs. 

Saving space on App page shouldn't be an issue;  we will soon implement a capability to group Apps or have better filtering.

**Comment by bacaron** [comment]
Okay that's fine! I'll get that done tomorrow.
