### ISSUE TITLE
store tract profile in product.json

### ISSUE THREAD

**Issue by soichih** [brain-life/app-tractanalysisprofiles#17]
This app currently generates the following product.json

```
{
    "quality_check": "All tracts analysis profiles were created successfully"
}
```

This should be updated to 

```
{
    "brainlife": [
        {"type": "success", "msg": "All tracts analysis profiles were created successfully"},
       ]
}
```

See https://brainlife.io/docs/apps/product/ for more info.

More importantly, though.. we should also output the content of tractprofile to product.json so that we can perform group analysis later on. I think we can try something like

```
{
    "tractprofile": {
         "tract_a": {
              fa: [0.23, 0.35, 0.34, ... 0.12, 0.8],
              md: [0.23, 0.35, 0.34, ... 0.12, 0.8]
         },
         "tract_b": {
              fa: [0.23, 0.35, 0.34, ... 0.12, 0.8],
              md: [0.23, 0.35, 0.34, ... 0.12, 0.8]
         }
    }
}
```

To keep the size of product.json small, I think we need to round the number down to 4th or 3rd decimal places.

**Comment by bacaron** [comment]
I'll get to this! Maybe will have some time tomorrow?

I agree we can round, I'm going to go with 4th decimal point.

**Comment by bacaron** [comment]
done!
