### ISSUE TITLE
Failes to run with noddi

### ISSUE THREAD

**Issue by soichih** [brain-life/app-tractanalysisprofiles#24]
I am running this App in NODDI mode by feeding noddi input data. 

The config.json looks like this

```
{
    "fiberbased": false,
    "numnodes": 200,
    "afq": "../5ed1a5f6529ab4ecb58320cf/5d8a60279842201ded7ec330/classification.mat",
    "dir": "../5ed5313d529ab4796c840564/dir.nii.gz",
    "ndi": "../5ed5313d529ab4796c840564/ndi.nii.gz",
    "isovf": "../5ed5313d529ab4796c840564/isovf.nii.gz",
    "odi": "../5ed5313d529ab4796c840564/odi.nii.gz",
    "tck": "../5ed1a5f6529ab4ecb58320cf/5d7c0635f59daff0888c380c/track.tck",
...
}
```

The app exits with this error message

> Please specify either tensor or noddi input (or both). You are trying to run this app with neither of them.

I think this is related to the recent update made for noddi datatype.

```
if ~isfield(config,'ad') && ~isfield(config,'icvf')
    display('Please specify either tensor or noddi input (or both). You are trying to run this app with neither of them.');
    exit
end

```

I believe all references to "icvf" should be renamed to isovf?

**Comment by francopestilli** [comment]
@bacaron I think might be a lingering issue related to your recent changes.

**Comment by bacaron** [comment]
What branch are you using?

**Comment by bacaron** [comment]
The issue had to do with a check at the very beginning of the script for a noddi input not being changed to reflect the new noddi config names. I'll patch this. Closing this issue.
