### ISSUE TITLE
Application failing. 

### ISSUE THREAD

**Issue by soichih** [brain-life/app-tractanalysisprofiles#7]
A user ran into following error message when he ran this app.

```
Error using fileparts (line 32)
Input must be a row vector of characters.

Error in niftiRead (line 46)


Error in main (line 23)

MATLAB:fileparts:MustBeChar
```

I can recreate this by simply running the app. 

I have following config

```
    "fa": true,
    "md": true,
    "rd": true,
    "ad": true
```

The code seems to be trying to open these as nifti?

```
nii_fa = niftiRead(fullfile(config.fa));
nii_md = niftiRead(fullfile(config.md));
nii_rd = niftiRead(fullfile(config.rd));
nii_ad = niftiRead(fullfile(config.ad));
```

Another issue with this app is that, it is failing to detect missing output files in `main`. If should be updated to check to see if `numfiles.txt` exists (if not, exit 1), then check the number of images generated?

**Comment by bacaron** [comment]
User needs to run dt6 to nifti converter app before running this app (https://github.com/brain-life/app-dt6tonifti).  Each individual tensor metric needs to be in it's own nifti structure in order for the app to work properly.

**Comment by soichih** [comment]
Brad,

I see following apps registered to use this git repo
> https://brainlife.io/warehouse/app/5a79e2e9e19e66005bdcd609

**Comment by soichih** [comment]
Brad,

I see following apps registered in BL to use this app.
> https://brainlife.io/warehouse/app/5a79e2e9e19e66005bdcd609
> https://brainlife.io/warehouse/app/5a037e0c8155510041652b72
> https://brainlife.io/warehouse/app/59ca5c03c27f5b0770add9cf

Do all 3 supposed to work? 

The issue I ran into was from this app..
> https://brainlife.io/warehouse/app/5a79e2e9e19e66005bdcd609

Also, since "tensor" datatype now includes all 4 files, user shouldn't have to select them individually. You can just ask for 1 and assume that you can find other 3 files under the same path?

**Comment by bacaron** [comment]
Test app should be deleted, just haven't gotten around to it. I was using it while implementing the changes just so people could still use the original app.

All three point to the same repo, just different branches. The code is nearly identical in both branches, but one is set up for NODDI files and the other tensor.

The way the new changes are set up, it's much easier to just have all 4 tensors run at once than have users select which ones they want. Most of the time you should generate plots for all 4. I don't have time over the next few weeks to work on making the change to select individual files, but can spend a scant amount of time the second week of March.

We can discuss more tomorrow.

**Comment by soichih** [comment]
I believe this is fixed..
